# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/neto/Projects/Topo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/neto/Projects/Topo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neto/Projects/Topo/CMakeFiles /home/neto/Projects/Topo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/neto/Projects/Topo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

#=============================================================================
# Target rules for targets named topo_engine

# Build rule for target.
topo_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 topo_engine
.PHONY : topo_engine

# fast build rule for target.
topo_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/build
.PHONY : topo_engine/fast

#=============================================================================
# Target rules for targets named topogen

# Build rule for target.
topogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 topogen
.PHONY : topogen

# fast build rule for target.
topogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/build
.PHONY : topogen/fast

#=============================================================================
# Target rules for targets named flecs

# Build rule for target.
flecs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flecs
.PHONY : flecs

# fast build rule for target.
flecs/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flecs-build/CMakeFiles/flecs.dir/build.make _deps/flecs-build/CMakeFiles/flecs.dir/build
.PHONY : flecs/fast

#=============================================================================
# Target rules for targets named flecs_static

# Build rule for target.
flecs_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flecs_static
.PHONY : flecs_static

# fast build rule for target.
flecs_static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/flecs-build/CMakeFiles/flecs_static.dir/build.make _deps/flecs-build/CMakeFiles/flecs_static.dir/build
.PHONY : flecs_static/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glm-build/glm/CMakeFiles/glm.dir/build.make _deps/glm-build/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

src/engine/app.o: src/engine/app.cpp.o
.PHONY : src/engine/app.o

# target to build an object file
src/engine/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/app.cpp.o
.PHONY : src/engine/app.cpp.o

src/engine/app.i: src/engine/app.cpp.i
.PHONY : src/engine/app.i

# target to preprocess a source file
src/engine/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/app.cpp.i
.PHONY : src/engine/app.cpp.i

src/engine/app.s: src/engine/app.cpp.s
.PHONY : src/engine/app.s

# target to generate assembly for a file
src/engine/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/app.cpp.s
.PHONY : src/engine/app.cpp.s

src/engine/camera/camera.o: src/engine/camera/camera.cpp.o
.PHONY : src/engine/camera/camera.o

# target to build an object file
src/engine/camera/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/camera/camera.cpp.o
.PHONY : src/engine/camera/camera.cpp.o

src/engine/camera/camera.i: src/engine/camera/camera.cpp.i
.PHONY : src/engine/camera/camera.i

# target to preprocess a source file
src/engine/camera/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/camera/camera.cpp.i
.PHONY : src/engine/camera/camera.cpp.i

src/engine/camera/camera.s: src/engine/camera/camera.cpp.s
.PHONY : src/engine/camera/camera.s

# target to generate assembly for a file
src/engine/camera/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/camera/camera.cpp.s
.PHONY : src/engine/camera/camera.cpp.s

src/engine/core/asset_manager.o: src/engine/core/asset_manager.cpp.o
.PHONY : src/engine/core/asset_manager.o

# target to build an object file
src/engine/core/asset_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/core/asset_manager.cpp.o
.PHONY : src/engine/core/asset_manager.cpp.o

src/engine/core/asset_manager.i: src/engine/core/asset_manager.cpp.i
.PHONY : src/engine/core/asset_manager.i

# target to preprocess a source file
src/engine/core/asset_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/core/asset_manager.cpp.i
.PHONY : src/engine/core/asset_manager.cpp.i

src/engine/core/asset_manager.s: src/engine/core/asset_manager.cpp.s
.PHONY : src/engine/core/asset_manager.s

# target to generate assembly for a file
src/engine/core/asset_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/core/asset_manager.cpp.s
.PHONY : src/engine/core/asset_manager.cpp.s

src/engine/gpu/gpu.o: src/engine/gpu/gpu.cpp.o
.PHONY : src/engine/gpu/gpu.o

# target to build an object file
src/engine/gpu/gpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/gpu/gpu.cpp.o
.PHONY : src/engine/gpu/gpu.cpp.o

src/engine/gpu/gpu.i: src/engine/gpu/gpu.cpp.i
.PHONY : src/engine/gpu/gpu.i

# target to preprocess a source file
src/engine/gpu/gpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/gpu/gpu.cpp.i
.PHONY : src/engine/gpu/gpu.cpp.i

src/engine/gpu/gpu.s: src/engine/gpu/gpu.cpp.s
.PHONY : src/engine/gpu/gpu.s

# target to generate assembly for a file
src/engine/gpu/gpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/gpu/gpu.cpp.s
.PHONY : src/engine/gpu/gpu.cpp.s

src/engine/input/input.o: src/engine/input/input.cpp.o
.PHONY : src/engine/input/input.o

# target to build an object file
src/engine/input/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/input/input.cpp.o
.PHONY : src/engine/input/input.cpp.o

src/engine/input/input.i: src/engine/input/input.cpp.i
.PHONY : src/engine/input/input.i

# target to preprocess a source file
src/engine/input/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/input/input.cpp.i
.PHONY : src/engine/input/input.cpp.i

src/engine/input/input.s: src/engine/input/input.cpp.s
.PHONY : src/engine/input/input.s

# target to generate assembly for a file
src/engine/input/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/input/input.cpp.s
.PHONY : src/engine/input/input.cpp.s

src/engine/render/background.o: src/engine/render/background.cpp.o
.PHONY : src/engine/render/background.o

# target to build an object file
src/engine/render/background.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/background.cpp.o
.PHONY : src/engine/render/background.cpp.o

src/engine/render/background.i: src/engine/render/background.cpp.i
.PHONY : src/engine/render/background.i

# target to preprocess a source file
src/engine/render/background.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/background.cpp.i
.PHONY : src/engine/render/background.cpp.i

src/engine/render/background.s: src/engine/render/background.cpp.s
.PHONY : src/engine/render/background.s

# target to generate assembly for a file
src/engine/render/background.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/background.cpp.s
.PHONY : src/engine/render/background.cpp.s

src/engine/render/render_system.o: src/engine/render/render_system.cpp.o
.PHONY : src/engine/render/render_system.o

# target to build an object file
src/engine/render/render_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/render_system.cpp.o
.PHONY : src/engine/render/render_system.cpp.o

src/engine/render/render_system.i: src/engine/render/render_system.cpp.i
.PHONY : src/engine/render/render_system.i

# target to preprocess a source file
src/engine/render/render_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/render_system.cpp.i
.PHONY : src/engine/render/render_system.cpp.i

src/engine/render/render_system.s: src/engine/render/render_system.cpp.s
.PHONY : src/engine/render/render_system.s

# target to generate assembly for a file
src/engine/render/render_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/render_system.cpp.s
.PHONY : src/engine/render/render_system.cpp.s

src/engine/render/sprite.o: src/engine/render/sprite.cpp.o
.PHONY : src/engine/render/sprite.o

# target to build an object file
src/engine/render/sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/sprite.cpp.o
.PHONY : src/engine/render/sprite.cpp.o

src/engine/render/sprite.i: src/engine/render/sprite.cpp.i
.PHONY : src/engine/render/sprite.i

# target to preprocess a source file
src/engine/render/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/sprite.cpp.i
.PHONY : src/engine/render/sprite.cpp.i

src/engine/render/sprite.s: src/engine/render/sprite.cpp.s
.PHONY : src/engine/render/sprite.s

# target to generate assembly for a file
src/engine/render/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/render/sprite.cpp.s
.PHONY : src/engine/render/sprite.cpp.s

src/engine/ui/imgui_ui.o: src/engine/ui/imgui_ui.cpp.o
.PHONY : src/engine/ui/imgui_ui.o

# target to build an object file
src/engine/ui/imgui_ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/ui/imgui_ui.cpp.o
.PHONY : src/engine/ui/imgui_ui.cpp.o

src/engine/ui/imgui_ui.i: src/engine/ui/imgui_ui.cpp.i
.PHONY : src/engine/ui/imgui_ui.i

# target to preprocess a source file
src/engine/ui/imgui_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/ui/imgui_ui.cpp.i
.PHONY : src/engine/ui/imgui_ui.cpp.i

src/engine/ui/imgui_ui.s: src/engine/ui/imgui_ui.cpp.s
.PHONY : src/engine/ui/imgui_ui.s

# target to generate assembly for a file
src/engine/ui/imgui_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topo_engine.dir/build.make CMakeFiles/topo_engine.dir/src/engine/ui/imgui_ui.cpp.s
.PHONY : src/engine/ui/imgui_ui.cpp.s

src/game/main.o: src/game/main.cpp.o
.PHONY : src/game/main.o

# target to build an object file
src/game/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/main.cpp.o
.PHONY : src/game/main.cpp.o

src/game/main.i: src/game/main.cpp.i
.PHONY : src/game/main.i

# target to preprocess a source file
src/game/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/main.cpp.i
.PHONY : src/game/main.cpp.i

src/game/main.s: src/game/main.cpp.s
.PHONY : src/game/main.s

# target to generate assembly for a file
src/game/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/main.cpp.s
.PHONY : src/game/main.cpp.s

src/game/terrain/basalt.o: src/game/terrain/basalt.cpp.o
.PHONY : src/game/terrain/basalt.o

# target to build an object file
src/game/terrain/basalt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/basalt.cpp.o
.PHONY : src/game/terrain/basalt.cpp.o

src/game/terrain/basalt.i: src/game/terrain/basalt.cpp.i
.PHONY : src/game/terrain/basalt.i

# target to preprocess a source file
src/game/terrain/basalt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/basalt.cpp.i
.PHONY : src/game/terrain/basalt.cpp.i

src/game/terrain/basalt.s: src/game/terrain/basalt.cpp.s
.PHONY : src/game/terrain/basalt.s

# target to generate assembly for a file
src/game/terrain/basalt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/basalt.cpp.s
.PHONY : src/game/terrain/basalt.cpp.s

src/game/terrain/contour.o: src/game/terrain/contour.cpp.o
.PHONY : src/game/terrain/contour.o

# target to build an object file
src/game/terrain/contour.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/contour.cpp.o
.PHONY : src/game/terrain/contour.cpp.o

src/game/terrain/contour.i: src/game/terrain/contour.cpp.i
.PHONY : src/game/terrain/contour.i

# target to preprocess a source file
src/game/terrain/contour.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/contour.cpp.i
.PHONY : src/game/terrain/contour.cpp.i

src/game/terrain/contour.s: src/game/terrain/contour.cpp.s
.PHONY : src/game/terrain/contour.s

# target to generate assembly for a file
src/game/terrain/contour.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/contour.cpp.s
.PHONY : src/game/terrain/contour.cpp.s

src/game/terrain/delve_render.o: src/game/terrain/delve_render.cpp.o
.PHONY : src/game/terrain/delve_render.o

# target to build an object file
src/game/terrain/delve_render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/delve_render.cpp.o
.PHONY : src/game/terrain/delve_render.cpp.o

src/game/terrain/delve_render.i: src/game/terrain/delve_render.cpp.i
.PHONY : src/game/terrain/delve_render.i

# target to preprocess a source file
src/game/terrain/delve_render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/delve_render.cpp.i
.PHONY : src/game/terrain/delve_render.cpp.i

src/game/terrain/delve_render.s: src/game/terrain/delve_render.cpp.s
.PHONY : src/game/terrain/delve_render.s

# target to generate assembly for a file
src/game/terrain/delve_render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/delve_render.cpp.s
.PHONY : src/game/terrain/delve_render.cpp.s

src/game/terrain/detail.o: src/game/terrain/detail.cpp.o
.PHONY : src/game/terrain/detail.o

# target to build an object file
src/game/terrain/detail.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/detail.cpp.o
.PHONY : src/game/terrain/detail.cpp.o

src/game/terrain/detail.i: src/game/terrain/detail.cpp.i
.PHONY : src/game/terrain/detail.i

# target to preprocess a source file
src/game/terrain/detail.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/detail.cpp.i
.PHONY : src/game/terrain/detail.cpp.i

src/game/terrain/detail.s: src/game/terrain/detail.cpp.s
.PHONY : src/game/terrain/detail.s

# target to generate assembly for a file
src/game/terrain/detail.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/detail.cpp.s
.PHONY : src/game/terrain/detail.cpp.s

src/game/terrain/hex.o: src/game/terrain/hex.cpp.o
.PHONY : src/game/terrain/hex.o

# target to build an object file
src/game/terrain/hex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/hex.cpp.o
.PHONY : src/game/terrain/hex.cpp.o

src/game/terrain/hex.i: src/game/terrain/hex.cpp.i
.PHONY : src/game/terrain/hex.i

# target to preprocess a source file
src/game/terrain/hex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/hex.cpp.i
.PHONY : src/game/terrain/hex.cpp.i

src/game/terrain/hex.s: src/game/terrain/hex.cpp.s
.PHONY : src/game/terrain/hex.s

# target to generate assembly for a file
src/game/terrain/hex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/hex.cpp.s
.PHONY : src/game/terrain/hex.cpp.s

src/game/terrain/isometric.o: src/game/terrain/isometric.cpp.o
.PHONY : src/game/terrain/isometric.o

# target to build an object file
src/game/terrain/isometric.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/isometric.cpp.o
.PHONY : src/game/terrain/isometric.cpp.o

src/game/terrain/isometric.i: src/game/terrain/isometric.cpp.i
.PHONY : src/game/terrain/isometric.i

# target to preprocess a source file
src/game/terrain/isometric.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/isometric.cpp.i
.PHONY : src/game/terrain/isometric.cpp.i

src/game/terrain/isometric.s: src/game/terrain/isometric.cpp.s
.PHONY : src/game/terrain/isometric.s

# target to generate assembly for a file
src/game/terrain/isometric.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/isometric.cpp.s
.PHONY : src/game/terrain/isometric.cpp.s

src/game/terrain/lava.o: src/game/terrain/lava.cpp.o
.PHONY : src/game/terrain/lava.o

# target to build an object file
src/game/terrain/lava.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/lava.cpp.o
.PHONY : src/game/terrain/lava.cpp.o

src/game/terrain/lava.i: src/game/terrain/lava.cpp.i
.PHONY : src/game/terrain/lava.i

# target to preprocess a source file
src/game/terrain/lava.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/lava.cpp.i
.PHONY : src/game/terrain/lava.cpp.i

src/game/terrain/lava.s: src/game/terrain/lava.cpp.s
.PHONY : src/game/terrain/lava.s

# target to generate assembly for a file
src/game/terrain/lava.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/lava.cpp.s
.PHONY : src/game/terrain/lava.cpp.s

src/game/terrain/map_gen.o: src/game/terrain/map_gen.cpp.o
.PHONY : src/game/terrain/map_gen.o

# target to build an object file
src/game/terrain/map_gen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/map_gen.cpp.o
.PHONY : src/game/terrain/map_gen.cpp.o

src/game/terrain/map_gen.i: src/game/terrain/map_gen.cpp.i
.PHONY : src/game/terrain/map_gen.i

# target to preprocess a source file
src/game/terrain/map_gen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/map_gen.cpp.i
.PHONY : src/game/terrain/map_gen.cpp.i

src/game/terrain/map_gen.s: src/game/terrain/map_gen.cpp.s
.PHONY : src/game/terrain/map_gen.s

# target to generate assembly for a file
src/game/terrain/map_gen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/map_gen.cpp.s
.PHONY : src/game/terrain/map_gen.cpp.s

src/game/terrain/noise.o: src/game/terrain/noise.cpp.o
.PHONY : src/game/terrain/noise.o

# target to build an object file
src/game/terrain/noise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise.cpp.o
.PHONY : src/game/terrain/noise.cpp.o

src/game/terrain/noise.i: src/game/terrain/noise.cpp.i
.PHONY : src/game/terrain/noise.i

# target to preprocess a source file
src/game/terrain/noise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise.cpp.i
.PHONY : src/game/terrain/noise.cpp.i

src/game/terrain/noise.s: src/game/terrain/noise.cpp.s
.PHONY : src/game/terrain/noise.s

# target to generate assembly for a file
src/game/terrain/noise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise.cpp.s
.PHONY : src/game/terrain/noise.cpp.s

src/game/terrain/noise_composer.o: src/game/terrain/noise_composer.cpp.o
.PHONY : src/game/terrain/noise_composer.o

# target to build an object file
src/game/terrain/noise_composer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise_composer.cpp.o
.PHONY : src/game/terrain/noise_composer.cpp.o

src/game/terrain/noise_composer.i: src/game/terrain/noise_composer.cpp.i
.PHONY : src/game/terrain/noise_composer.i

# target to preprocess a source file
src/game/terrain/noise_composer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise_composer.cpp.i
.PHONY : src/game/terrain/noise_composer.cpp.i

src/game/terrain/noise_composer.s: src/game/terrain/noise_composer.cpp.s
.PHONY : src/game/terrain/noise_composer.s

# target to generate assembly for a file
src/game/terrain/noise_composer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise_composer.cpp.s
.PHONY : src/game/terrain/noise_composer.cpp.s

src/game/terrain/noise_layers.o: src/game/terrain/noise_layers.cpp.o
.PHONY : src/game/terrain/noise_layers.o

# target to build an object file
src/game/terrain/noise_layers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise_layers.cpp.o
.PHONY : src/game/terrain/noise_layers.cpp.o

src/game/terrain/noise_layers.i: src/game/terrain/noise_layers.cpp.i
.PHONY : src/game/terrain/noise_layers.i

# target to preprocess a source file
src/game/terrain/noise_layers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise_layers.cpp.i
.PHONY : src/game/terrain/noise_layers.cpp.i

src/game/terrain/noise_layers.s: src/game/terrain/noise_layers.cpp.s
.PHONY : src/game/terrain/noise_layers.s

# target to generate assembly for a file
src/game/terrain/noise_layers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/noise_layers.cpp.s
.PHONY : src/game/terrain/noise_layers.cpp.s

src/game/terrain/terrain_generator.o: src/game/terrain/terrain_generator.cpp.o
.PHONY : src/game/terrain/terrain_generator.o

# target to build an object file
src/game/terrain/terrain_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_generator.cpp.o
.PHONY : src/game/terrain/terrain_generator.cpp.o

src/game/terrain/terrain_generator.i: src/game/terrain/terrain_generator.cpp.i
.PHONY : src/game/terrain/terrain_generator.i

# target to preprocess a source file
src/game/terrain/terrain_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_generator.cpp.i
.PHONY : src/game/terrain/terrain_generator.cpp.i

src/game/terrain/terrain_generator.s: src/game/terrain/terrain_generator.cpp.s
.PHONY : src/game/terrain/terrain_generator.s

# target to generate assembly for a file
src/game/terrain/terrain_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_generator.cpp.s
.PHONY : src/game/terrain/terrain_generator.cpp.s

src/game/terrain/terrain_mesh.o: src/game/terrain/terrain_mesh.cpp.o
.PHONY : src/game/terrain/terrain_mesh.o

# target to build an object file
src/game/terrain/terrain_mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_mesh.cpp.o
.PHONY : src/game/terrain/terrain_mesh.cpp.o

src/game/terrain/terrain_mesh.i: src/game/terrain/terrain_mesh.cpp.i
.PHONY : src/game/terrain/terrain_mesh.i

# target to preprocess a source file
src/game/terrain/terrain_mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_mesh.cpp.i
.PHONY : src/game/terrain/terrain_mesh.cpp.i

src/game/terrain/terrain_mesh.s: src/game/terrain/terrain_mesh.cpp.s
.PHONY : src/game/terrain/terrain_mesh.s

# target to generate assembly for a file
src/game/terrain/terrain_mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_mesh.cpp.s
.PHONY : src/game/terrain/terrain_mesh.cpp.s

src/game/terrain/terrain_renderer.o: src/game/terrain/terrain_renderer.cpp.o
.PHONY : src/game/terrain/terrain_renderer.o

# target to build an object file
src/game/terrain/terrain_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_renderer.cpp.o
.PHONY : src/game/terrain/terrain_renderer.cpp.o

src/game/terrain/terrain_renderer.i: src/game/terrain/terrain_renderer.cpp.i
.PHONY : src/game/terrain/terrain_renderer.i

# target to preprocess a source file
src/game/terrain/terrain_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_renderer.cpp.i
.PHONY : src/game/terrain/terrain_renderer.cpp.i

src/game/terrain/terrain_renderer.s: src/game/terrain/terrain_renderer.cpp.s
.PHONY : src/game/terrain/terrain_renderer.s

# target to generate assembly for a file
src/game/terrain/terrain_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/terrain/terrain_renderer.cpp.s
.PHONY : src/game/terrain/terrain_renderer.cpp.s

src/game/topo_game.o: src/game/topo_game.cpp.o
.PHONY : src/game/topo_game.o

# target to build an object file
src/game/topo_game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/topo_game.cpp.o
.PHONY : src/game/topo_game.cpp.o

src/game/topo_game.i: src/game/topo_game.cpp.i
.PHONY : src/game/topo_game.i

# target to preprocess a source file
src/game/topo_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/topo_game.cpp.i
.PHONY : src/game/topo_game.cpp.i

src/game/topo_game.s: src/game/topo_game.cpp.s
.PHONY : src/game/topo_game.s

# target to generate assembly for a file
src/game/topo_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/topogen.dir/build.make CMakeFiles/topogen.dir/src/game/topo_game.cpp.s
.PHONY : src/game/topo_game.cpp.s

third_party/imgui/backends/imgui_impl_sdl3.o: third_party/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_sdl3.o

# target to build an object file
third_party/imgui/backends/imgui_impl_sdl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdl3.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_sdl3.cpp.o

third_party/imgui/backends/imgui_impl_sdl3.i: third_party/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_sdl3.i

# target to preprocess a source file
third_party/imgui/backends/imgui_impl_sdl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdl3.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_sdl3.cpp.i

third_party/imgui/backends/imgui_impl_sdl3.s: third_party/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_sdl3.s

# target to generate assembly for a file
third_party/imgui/backends/imgui_impl_sdl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdl3.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_sdl3.cpp.s

third_party/imgui/backends/imgui_impl_sdlgpu3.o: third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_sdlgpu3.o

# target to build an object file
third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.o
.PHONY : third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.o

third_party/imgui/backends/imgui_impl_sdlgpu3.i: third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_sdlgpu3.i

# target to preprocess a source file
third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.i
.PHONY : third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.i

third_party/imgui/backends/imgui_impl_sdlgpu3.s: third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_sdlgpu3.s

# target to generate assembly for a file
third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.s
.PHONY : third_party/imgui/backends/imgui_impl_sdlgpu3.cpp.s

third_party/imgui/imgui.o: third_party/imgui/imgui.cpp.o
.PHONY : third_party/imgui/imgui.o

# target to build an object file
third_party/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui.cpp.o
.PHONY : third_party/imgui/imgui.cpp.o

third_party/imgui/imgui.i: third_party/imgui/imgui.cpp.i
.PHONY : third_party/imgui/imgui.i

# target to preprocess a source file
third_party/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui.cpp.i
.PHONY : third_party/imgui/imgui.cpp.i

third_party/imgui/imgui.s: third_party/imgui/imgui.cpp.s
.PHONY : third_party/imgui/imgui.s

# target to generate assembly for a file
third_party/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui.cpp.s
.PHONY : third_party/imgui/imgui.cpp.s

third_party/imgui/imgui_draw.o: third_party/imgui/imgui_draw.cpp.o
.PHONY : third_party/imgui/imgui_draw.o

# target to build an object file
third_party/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_draw.cpp.o
.PHONY : third_party/imgui/imgui_draw.cpp.o

third_party/imgui/imgui_draw.i: third_party/imgui/imgui_draw.cpp.i
.PHONY : third_party/imgui/imgui_draw.i

# target to preprocess a source file
third_party/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_draw.cpp.i
.PHONY : third_party/imgui/imgui_draw.cpp.i

third_party/imgui/imgui_draw.s: third_party/imgui/imgui_draw.cpp.s
.PHONY : third_party/imgui/imgui_draw.s

# target to generate assembly for a file
third_party/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_draw.cpp.s
.PHONY : third_party/imgui/imgui_draw.cpp.s

third_party/imgui/imgui_tables.o: third_party/imgui/imgui_tables.cpp.o
.PHONY : third_party/imgui/imgui_tables.o

# target to build an object file
third_party/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_tables.cpp.o
.PHONY : third_party/imgui/imgui_tables.cpp.o

third_party/imgui/imgui_tables.i: third_party/imgui/imgui_tables.cpp.i
.PHONY : third_party/imgui/imgui_tables.i

# target to preprocess a source file
third_party/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_tables.cpp.i
.PHONY : third_party/imgui/imgui_tables.cpp.i

third_party/imgui/imgui_tables.s: third_party/imgui/imgui_tables.cpp.s
.PHONY : third_party/imgui/imgui_tables.s

# target to generate assembly for a file
third_party/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_tables.cpp.s
.PHONY : third_party/imgui/imgui_tables.cpp.s

third_party/imgui/imgui_widgets.o: third_party/imgui/imgui_widgets.cpp.o
.PHONY : third_party/imgui/imgui_widgets.o

# target to build an object file
third_party/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_widgets.cpp.o
.PHONY : third_party/imgui/imgui_widgets.cpp.o

third_party/imgui/imgui_widgets.i: third_party/imgui/imgui_widgets.cpp.i
.PHONY : third_party/imgui/imgui_widgets.i

# target to preprocess a source file
third_party/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_widgets.cpp.i
.PHONY : third_party/imgui/imgui_widgets.cpp.i

third_party/imgui/imgui_widgets.s: third_party/imgui/imgui_widgets.cpp.s
.PHONY : third_party/imgui/imgui_widgets.s

# target to generate assembly for a file
third_party/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/third_party/imgui/imgui_widgets.cpp.s
.PHONY : third_party/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... shaders"
	@echo "... flecs"
	@echo "... flecs_static"
	@echo "... glm"
	@echo "... imgui"
	@echo "... topo_engine"
	@echo "... topogen"
	@echo "... src/engine/app.o"
	@echo "... src/engine/app.i"
	@echo "... src/engine/app.s"
	@echo "... src/engine/camera/camera.o"
	@echo "... src/engine/camera/camera.i"
	@echo "... src/engine/camera/camera.s"
	@echo "... src/engine/core/asset_manager.o"
	@echo "... src/engine/core/asset_manager.i"
	@echo "... src/engine/core/asset_manager.s"
	@echo "... src/engine/gpu/gpu.o"
	@echo "... src/engine/gpu/gpu.i"
	@echo "... src/engine/gpu/gpu.s"
	@echo "... src/engine/input/input.o"
	@echo "... src/engine/input/input.i"
	@echo "... src/engine/input/input.s"
	@echo "... src/engine/render/background.o"
	@echo "... src/engine/render/background.i"
	@echo "... src/engine/render/background.s"
	@echo "... src/engine/render/render_system.o"
	@echo "... src/engine/render/render_system.i"
	@echo "... src/engine/render/render_system.s"
	@echo "... src/engine/render/sprite.o"
	@echo "... src/engine/render/sprite.i"
	@echo "... src/engine/render/sprite.s"
	@echo "... src/engine/ui/imgui_ui.o"
	@echo "... src/engine/ui/imgui_ui.i"
	@echo "... src/engine/ui/imgui_ui.s"
	@echo "... src/game/main.o"
	@echo "... src/game/main.i"
	@echo "... src/game/main.s"
	@echo "... src/game/terrain/basalt.o"
	@echo "... src/game/terrain/basalt.i"
	@echo "... src/game/terrain/basalt.s"
	@echo "... src/game/terrain/contour.o"
	@echo "... src/game/terrain/contour.i"
	@echo "... src/game/terrain/contour.s"
	@echo "... src/game/terrain/delve_render.o"
	@echo "... src/game/terrain/delve_render.i"
	@echo "... src/game/terrain/delve_render.s"
	@echo "... src/game/terrain/detail.o"
	@echo "... src/game/terrain/detail.i"
	@echo "... src/game/terrain/detail.s"
	@echo "... src/game/terrain/hex.o"
	@echo "... src/game/terrain/hex.i"
	@echo "... src/game/terrain/hex.s"
	@echo "... src/game/terrain/isometric.o"
	@echo "... src/game/terrain/isometric.i"
	@echo "... src/game/terrain/isometric.s"
	@echo "... src/game/terrain/lava.o"
	@echo "... src/game/terrain/lava.i"
	@echo "... src/game/terrain/lava.s"
	@echo "... src/game/terrain/map_gen.o"
	@echo "... src/game/terrain/map_gen.i"
	@echo "... src/game/terrain/map_gen.s"
	@echo "... src/game/terrain/noise.o"
	@echo "... src/game/terrain/noise.i"
	@echo "... src/game/terrain/noise.s"
	@echo "... src/game/terrain/noise_composer.o"
	@echo "... src/game/terrain/noise_composer.i"
	@echo "... src/game/terrain/noise_composer.s"
	@echo "... src/game/terrain/noise_layers.o"
	@echo "... src/game/terrain/noise_layers.i"
	@echo "... src/game/terrain/noise_layers.s"
	@echo "... src/game/terrain/terrain_generator.o"
	@echo "... src/game/terrain/terrain_generator.i"
	@echo "... src/game/terrain/terrain_generator.s"
	@echo "... src/game/terrain/terrain_mesh.o"
	@echo "... src/game/terrain/terrain_mesh.i"
	@echo "... src/game/terrain/terrain_mesh.s"
	@echo "... src/game/terrain/terrain_renderer.o"
	@echo "... src/game/terrain/terrain_renderer.i"
	@echo "... src/game/terrain/terrain_renderer.s"
	@echo "... src/game/topo_game.o"
	@echo "... src/game/topo_game.i"
	@echo "... src/game/topo_game.s"
	@echo "... third_party/imgui/backends/imgui_impl_sdl3.o"
	@echo "... third_party/imgui/backends/imgui_impl_sdl3.i"
	@echo "... third_party/imgui/backends/imgui_impl_sdl3.s"
	@echo "... third_party/imgui/backends/imgui_impl_sdlgpu3.o"
	@echo "... third_party/imgui/backends/imgui_impl_sdlgpu3.i"
	@echo "... third_party/imgui/backends/imgui_impl_sdlgpu3.s"
	@echo "... third_party/imgui/imgui.o"
	@echo "... third_party/imgui/imgui.i"
	@echo "... third_party/imgui/imgui.s"
	@echo "... third_party/imgui/imgui_draw.o"
	@echo "... third_party/imgui/imgui_draw.i"
	@echo "... third_party/imgui/imgui_draw.s"
	@echo "... third_party/imgui/imgui_tables.o"
	@echo "... third_party/imgui/imgui_tables.i"
	@echo "... third_party/imgui/imgui_tables.s"
	@echo "... third_party/imgui/imgui_widgets.o"
	@echo "... third_party/imgui/imgui_widgets.i"
	@echo "... third_party/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

