// ─── Shared Types ────────────────────────────────────────────────────────────

export interface ToolMeta {
  name: string;
  category: string;
  keywords: string[];
  prerequisites: string[];
  enables: string[];
  description: string;
  cost: "cheap" | "moderate" | "expensive";
}

export const TOOL_REGISTRY: ToolMeta[] = [
  // Build tools
  {
    name: "build_configure",
    category: "build",
    keywords: ["cmake", "configure", "setup", "build type", "debug", "release"],
    prerequisites: [],
    enables: ["build_compile"],
    description: "Run cmake configure step. Required before first build or after CMakeLists.txt changes.",
    cost: "moderate",
  },
  {
    name: "build_compile",
    category: "build",
    keywords: ["build", "compile", "make", "link", "error", "warning"],
    prerequisites: ["build_configure (if CMakeLists.txt changed)"],
    enables: ["test_run"],
    description: "Compile the project. Returns compiler output including errors.",
    cost: "expensive",
  },
  {
    name: "build_clean",
    category: "build",
    keywords: ["clean", "reset", "corrupted", "rebuild"],
    prerequisites: [],
    enables: ["build_configure"],
    description: "Clean the build directory. Use when build state is corrupted.",
    cost: "cheap",
  },
  // Test tools
  {
    name: "test_run",
    category: "test",
    keywords: ["test", "verify", "check", "pass", "fail", "metrics", "quantitative"],
    prerequisites: ["build_compile"],
    enables: [],
    description: "Build and run delve_tests. Returns JSON with pass/fail per test.",
    cost: "expensive",
  },
  {
    name: "test_list",
    category: "test",
    keywords: ["test", "list", "discover", "available", "registered"],
    prerequisites: [],
    enables: [],
    description: "List all registered test cases by scanning DELVE_TEST macros.",
    cost: "cheap",
  },
  // Terrain tools
  {
    name: "terrain_list_palettes",
    category: "terrain",
    keywords: ["palette", "color", "theme", "biome", "tundra", "desert", "ocean"],
    prerequisites: [],
    enables: [],
    description: "List all terrain palettes defined in palettes.h.",
    cost: "cheap",
  },
  {
    name: "terrain_get_config",
    category: "terrain",
    keywords: ["config", "parameters", "noise", "elevation", "worley", "settings"],
    prerequisites: [],
    enables: ["terrain_set_config"],
    description: "Read terrain config from config.json (noise params, composition, display).",
    cost: "cheap",
  },
  {
    name: "terrain_set_config",
    category: "terrain",
    keywords: ["config", "update", "change", "parameters", "settings"],
    prerequisites: ["terrain_get_config"],
    enables: [],
    description: "Update terrain configuration in config.json.",
    cost: "cheap",
  },
  {
    name: "terrain_pipeline_info",
    category: "terrain",
    keywords: ["pipeline", "stage", "noise", "composition", "contour", "generation", "mesh", "rendering", "data flow"],
    prerequisites: [],
    enables: [],
    description: "Get info about a terrain pipeline stage: files, input/output, data flow.",
    cost: "cheap",
  },
  // Code intelligence tools
  {
    name: "code_list_subsystem",
    category: "code",
    keywords: ["files", "list", "directory", "subsystem", "engine", "terrain", "shader", "test"],
    prerequisites: [],
    enables: ["code_find_definition"],
    description: "List all source files in a subsystem directory.",
    cost: "cheap",
  },
  {
    name: "code_find_definition",
    category: "code",
    keywords: ["definition", "struct", "class", "function", "enum", "where", "find", "symbol"],
    prerequisites: [],
    enables: ["code_find_usages"],
    description: "Find where a symbol is defined (struct, class, function, enum).",
    cost: "cheap",
  },
  {
    name: "code_find_usages",
    category: "code",
    keywords: ["usage", "reference", "caller", "used", "import", "include"],
    prerequisites: [],
    enables: [],
    description: "Find where a symbol is used across the codebase.",
    cost: "cheap",
  },
  // Git tools
  {
    name: "git_status",
    category: "git",
    keywords: ["status", "branch", "staged", "modified", "untracked", "changes"],
    prerequisites: [],
    enables: [],
    description: "Get current git status: branch, staged/modified/untracked files.",
    cost: "cheap",
  },
  {
    name: "git_diff_from_main",
    category: "git",
    keywords: ["diff", "changes", "compare", "main", "branch"],
    prerequisites: [],
    enables: [],
    description: "Show files changed compared to main branch.",
    cost: "cheap",
  },
  // Project info
  {
    name: "project_overview",
    category: "project",
    keywords: ["overview", "structure", "architecture", "entry point", "build targets", "subsystems"],
    prerequisites: [],
    enables: ["code_list_subsystem", "terrain_pipeline_info"],
    description: "High-level project structure, build targets, and key entry points.",
    cost: "cheap",
  },
  // Metrics tools
  {
    name: "metrics_run",
    category: "metrics",
    keywords: ["metrics", "verify", "quantitative", "headless", "terrain", "mesh", "performance"],
    prerequisites: ["build_compile"],
    enables: ["metrics_read_domain"],
    description: "Run headless metrics pipeline. Produces per-domain JSON files (terrain, mesh, performance).",
    cost: "expensive",
  },
  {
    name: "metrics_read_domain",
    category: "metrics",
    keywords: ["metrics", "domain", "terrain", "mesh", "performance", "read", "analyze"],
    prerequisites: ["metrics_run"],
    enables: [],
    description: "Read a specific domain's metric JSON file from the metrics output.",
    cost: "cheap",
  },
  // Agent-app interaction tools
  {
    name: "app_launch",
    category: "agent-app",
    keywords: ["launch", "start", "run", "agent", "app", "ipc", "socket"],
    prerequisites: ["build_compile"],
    enables: ["app_get_state", "app_capture_frame", "app_send_input"],
    description: "Launch the Delve app in agent mode with IPC socket.",
    cost: "expensive",
  },
  {
    name: "app_get_state",
    category: "agent-app",
    keywords: ["state", "status", "frame", "camera", "terrain"],
    prerequisites: ["app_launch"],
    enables: [],
    description: "Get the current state of the running app via IPC.",
    cost: "cheap",
  },
  {
    name: "app_capture_frame",
    category: "agent-app",
    keywords: ["capture", "screenshot", "frame", "png", "image", "visual"],
    prerequisites: ["app_launch"],
    enables: ["app_compare_frames"],
    description: "Capture the current frame as a PNG file.",
    cost: "moderate",
  },
  {
    name: "app_send_input",
    category: "agent-app",
    keywords: ["input", "key", "keyboard", "press", "interact"],
    prerequisites: ["app_launch"],
    enables: [],
    description: "Send synthetic keyboard input to the running app.",
    cost: "cheap",
  },
  {
    name: "app_stop",
    category: "agent-app",
    keywords: ["stop", "quit", "exit", "shutdown", "close"],
    prerequisites: ["app_launch"],
    enables: [],
    description: "Stop the running Delve application gracefully.",
    cost: "cheap",
  },
  {
    name: "app_compare_frames",
    category: "agent-app",
    keywords: ["compare", "diff", "similarity", "visual", "regression"],
    prerequisites: ["app_capture_frame"],
    enables: [],
    description: "Compare two PNG frame captures for similarity percentage.",
    cost: "cheap",
  },
  // Viking tools
  {
    name: "viking_search",
    category: "viking",
    keywords: ["search", "semantic", "context", "codebase", "viking", "openviking"],
    prerequisites: [],
    enables: ["viking_read"],
    description: "Semantic search across OpenViking-indexed codebase resources.",
    cost: "moderate",
  },
  {
    name: "viking_read",
    category: "viking",
    keywords: ["read", "content", "resource", "viking", "uri", "file"],
    prerequisites: [],
    enables: [],
    description: "Read full content of a Viking-indexed resource by URI.",
    cost: "moderate",
  },
  {
    name: "viking_write_memory",
    category: "viking",
    keywords: ["write", "memory", "persist", "save", "viking", "note"],
    prerequisites: [],
    enables: [],
    description: "Write content to persistent Viking memory (viking://memories/ namespace).",
    cost: "cheap",
  },
];
